SMTP_SERVER: smtp.gmail.com
SMTP_PORT: 587
USERNAME: your_email@example.com
PASSWORD: "your_password"

TIMEZONE: 'Europe/Berlin'

PARTICIPANTS:
  - Chad <chad@somewhere.net>
  - Jen <jen@gmail.net>
  - Bill <Bill@somedomain.net>
  - Sharon <Sharon@hi.org>


# Warning -- if you mess this up you could get an infinite loop
COUPLES:
  - Chad, Jen    # Chad and Jen are married
  - Chad, Bill   # Chad and Bill are best friends
  - Bill, Sharon

LIMIT: 50 euro
DEATHLINE: Jan. 1
TEMPLATE: templates/mail.html

# From address should be the organizer in case participants have any questions
FROM: Secret Santa <your_email@example.com>
SUBJECT: Secret Santa message

